site_name: "shinyverse"
site_description: "A batteries included opinionated approach to building shiny apps in python"
site_url: "https://jameshwade.github.io/shinyverse"
repo_url: "https://github.com/jameshwade/shinyverse"
repo_name: "jameshwade/shinyverse"
site_dir: "site"
use_directory_urls: false
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/shinyverse]
copyright: Copyright &copy; 2024 James Wade
edit_uri: edit/main/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- API reference:
  - shinyverse: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md

theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- attr_list
- admonition
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: true

plugins:
- callouts
- search
- markdown-exec
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- mkdocstrings
- git-committers:
    repository: jameshwade/shinyverse

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/jameshwade
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/shinyverse/
