on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: PDM CI
    steps:
    - uses: actions/checkout@v3
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      # You are now able to use PDM in your workflow
    - name: Install dependencies
      run: pdm install
    - name: Build
      run: pdm build
